services:
  - type: web
    name: image-resizer-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p uploads
      chmod 755 uploads
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_ENV
        value: production
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/uploads
      - key: FLASK_APP
        value: main.py
      - key: SECRET_KEY
        value: 678bcbacb43b90dfa4e0962f9cf1535b66be277b3ffd66094988eb0b56d93e31 