services:
  - type: web
    name: image-resizer-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p uploads
      chmod 755 uploads
    startCommand: gunicorn "app:create_app(Config)"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_ENV
        value: production
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/uploads
      - key: FLASK_APP
        value: app
      - key: SECRET_KEY
        value: your-secret-key-here 